version: 2.1
########################
jobs:
  build:
    docker:
      image: circleci/node:13.8.0
    steps:
      # Checkout code over SSH, not HTTPS
      - checkout
      # Install the NPM package
      - run: npm i
      - save_cache:
          # Unique id for this cache 
          key: "myCache"
          # List of dir(s) added to the cache
          paths:
            - /src
      -run: npm run lint

  test:
    docker:
      image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - restrore_cache:
          key: "myCache"
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      image: circleci/node:13.8.0
    steps:
      - checkout
      - restrore_cache:
          key: "myCache"
      - #run: npm i
      - run: npm audit
      
workflows:
  myworkflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test