version: 2.1
########################
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      # Run the infra cloudformation script
      - run:
        command: |
          aws cloudformation create-stack \
          --stack-name $AWS_STACK_NAME \ 
          --template-body file://lmcfpoi/react-slingshot/.circleci/template.yml \ 
          --capabilities CAPABILITY_IAM \ 
          --region $AWS_DEFAULT_REGION
      
workflows:
  myworkflow:
    jobs:
      - create_infrastructure